<a href="https://colab.research.google.com/github/kny1209/test2/blob/main/AI/%EA%B0%95%EC%9D%98_8%EA%B8%B0_AI%EA%B0%9C%EB%A1%A0_3%EC%B0%A8%EC%8B%9C_02_%EA%B8%B0%EB%B3%B8_%ED%85%90%EC%84%9C(Tensor).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#텐서 (tensor)

## 2.1 텐서(Tensor) 소개


- 최근의 머신 러닝 시스템은 일반적으로 **텐서를 기본 데이터 구조**로 사용한다.  
- 데이터를 위한 컨테이너라고 생각하면 쉽게 이해할 수 있다.
- NumPy는 훌륭한 프레임워크지만, GPU를 사용하여 수치 연산을 가속화할 수는 없기 때문에 GPU연산이 가능한 PyTorch에서의 Tensor를 사용한다. (디바이스 선택이 수월함.)


  심층 신경망에서 GPU는 종종 50배 또는 그 이상의 속도 향상을 제공하기 때문에, 안타깝게도 NumPy는 딥러닝 프로그래밍에는 충분치 않다.


- **PyTorch 텐서(Tensor)는 개념적으로 NumPy 배열과 동일** : 텐서(Tensor)는 n-차원 배열이며, PyTorch는 이러한 텐서들의 연산을 위한 다양한 기능들을 제공한다.


> ### 텐서의 특성


-   축의 개수:  
    랭크(Rank)라고도 부르며, 넘파이 배열에서는 `ndim`을 통해 확인할 수 있다.  
   
-   크기:  
    텐서의 각 축을 따라 얼마나 많은 차원이 있는지를 나타낸 튜플 넘파이 배열에서는 `shape`을 통해 확인할 수 있다.  


-   데이터 타입:  
    텐서에 포함된 데이터 타입이다.  
    타입은 float32, unit8(부호없는 int), float64 등이 될 수 있으며 문자열은 지원하지 않는다. `dtpye` 속성으로 데이터를 확인할 수 있다.


In [5]:
# 스칼라 (0차원)
# 하나의 숫자만을 담고 있는 텐서 (0차원 텐서)
# 스칼라 축 개수는 0개

import torch
import numpy as np

scalar = np.array(10)
print(scalar)   # 10
print(scalar.ndim)  # 0
print(scalar.shape) # 차원 X >> 빈 튜플 출력

10
0
()


In [7]:
# 벡터 (1D 텐서)
# >> 숫자의 배열을 벡터라 함 (1차원 텐서)
# 벡터의 축의 개수 : 1개

import torch
import numpy as np

vector = np.array([1,2,3,4,5])
print(vector)   # [1 2 3 4 5]
print(vector.ndim)  # 1 : 차원
print(vector.shape) # (5,) : 배열의 크기

[1 2 3 4 5]
1
(5,)


In [8]:
# 행렬 (2D tensor)
# 벡터들의 배열 : 행렬 (2차원 텐서)
# 행렬에는 행과 열 2가지 축 존재

import torch
import numpy as np

matrix = \
np.array([[1,2,3],
          [4,5,6]])

In [9]:
print(matrix)
print(matrix.ndim)  # 2차원
print(matrix.shape) # (2,3) 2개의 배열 각 배열마다 3개의 원소

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [13]:
# 고차원 텐서
# 행렬들을 하나의 새로운 배열을 합치면 숫자로 채워진 직육면체가 되는데 이는 3D Tensor이다.
# 딥러닝에서는 보통 5차원 텐서까지 다루게 된다.
import torch
import numpy as np

tensor3d = \
np.arange(24).reshape(2,3,-1)

print(tensor3d)
print(tensor3d.ndim)    # 3차원
print(tensor3d.shape)   # 2개의 3*4 행렬 포함

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)


> ### Tensor의 Shape


넘파이의 배열에서 `shape`를 이용하여 텐서의 크기를 알아볼 경우 return값은 다음과 같다  

**1차원 : (열,)**  
**2차원 : (행, 열)**  
**3차원 : (깊이, 행, 열)**  

즉, 열의 기준이 되어 차원이 늘어날수록 늘어난 차원의 크기가 열의 앞에 추가된다고 생각하면 된다.  
머신러닝에서 사용하는 train\_data의 shape은 다음과 같다.  


**1\. 벡터 데이터: (samples, features) 2D tensor**
집값 예측 문제라고 생각하고 주어진 데이터가 100개의 연식, 동네, 역세권의 유무에 따른 데이터라고 하면 (100, 3)크기의 텐서에 저장될 수 있다.  


**2\. 이미지: (samples, height, width, channels) 4D tensor**
채널 우선방식 과 채널 마지막 방식 으로 나뉘지만 보통의 경우 100 장의 28x28의 컬러 이미지라면 (100, 28, 28, 3)크기의 텐서에 저장될 수 있다.  


**3\. 동영상: (samples, Time(frames), height, width, channels) 5D tenesor**
- FPS (Frame per Second)

In [15]:
import numpy as np
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)

# (60000, 28, 28)
# 28x28 이미지 60000장

(60000, 28, 28)


In [20]:
use_images = train_images[:100,:,:]
print(use_images.shape)

# 일반적으로 딥러닝에서 사용하는 모든 데이터 텐서 첫번째 축(axis=0)은 샘플 축(샘플 개수)임


(100, 28, 28)


In [25]:
# 6만장 데이터 중에서 위쪽 절반만 사용하고 싶은 경우
use_images = train_images[:,:14,:]
print(use_images.shape)

(60000, 14, 28)


#### ※ Tensor과 Ndarray
- 텐서 (Tensor)는 NumPy 어레이와 비슷하지만, 텐서는 GPU, TPU와 같은 가속기에서 사용할 수 있고, 텐서는 값을 변경할 수 없습니다.




먼저 Pytorch에서 주로 다루는 데이터 자료형인 Tensor과 Numpy에서 주로 다루는 데이터 자료형인 ndarray는 다차원 배열과 배열 생성 시 다양한 데이터 타입 적용이 가능하지만 주요한 차이점이 존재합니다.


우선 가장 중요한 차이점은 GPU를 활용한 연산이 가능한가? 이며, 그 외로 중요한 기능들에서 차이점이 있습니다.


텐서 생성하기

- 텐서는 파이토치에서 스칼라, 벡터, 행렬 같은 개념으로 연산에 사용하는 기본적인 자료구조이며 다차원 배열로 표현할 수 있습니다.
- 파이썬 numpy의 ndarray와 유사합니다.(n차원의 배열 객체)
- 텐서는 n차원으로 구성되어 있는데 0차원은 스칼라, 1차원은 벡터, 2차원은 행렬, 3차원부터 텐서입니다.
- 1차원 텐서, 2차원 텐서, 3차원 텐서라고도 합니다.
- torch 패키지를 임포트하고 tensor 함수를 이용하여 텐서를 생성할 수 있습니다.

In [29]:
import torch

# 1차원 텐서
a = torch.tensor([1,2,3,4,5])
print(a)
print(a.size())     # 텐서 크기 확인

tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [36]:
import torch

# 2차원 텐서
x1 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(x1)
print()
print(x1.shape)
print(x1.size())    # tensor 크기 (행, 열)
print()
print('rank(차원) :',x1.dim())  # 메소드
print(x1.ndim)  # 속성

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

torch.Size([3, 3])
torch.Size([3, 3])

rank(차원) : 2
2


In [40]:
import torch

# 3행 2열 리스트로 2차원 텐서 생성
data = [[1,2],[3,4],[5,6]]

# 텐서 변환
x2 = torch.tensor(data)
print(x2)
print(x2.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [48]:
# 3차원 텐서
# 2차원 텐서를 대괄호로 감쌈

x3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(x3)
print(x3.shape)

# torch.Size([1, 3, 3])
# 첫번째 차원(깊이) 크기 : 1
# 두번째 차원(행) 크기 : 3
# 세번째 차원(열) 크기 : 3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])


In [54]:
# Numpy 배열과 pytorch tensor 변환

import torch
import numpy as np

x3_1 = [[1,2,3],[4,5,6],[7,8,9]]
data_np = np.array(x3_1)  # numpy 배열
print(data_np)
print()
# x3_torch = torch.from_numpy(data_np)    # tensor 변환
x3_torch = torch.tensor(data_np)
print(x3_torch)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# 특정 값으로 생성

In [61]:
import torch
# 0으로 채워진 텐서
tensor_zeros = torch.zeros(2,3)
print(tensor_zeros)
print()

# 1로 채워잔 텐서
tensor_ones = torch.ones(2,3)
print(tensor_ones)
print()

# 특정값으로 채워진 텐서
tensor_full = torch.full((2,3),7)
print(tensor_full)
# 2행 3열 2차원 텐서 생성 >> 7로 채워

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[7, 7, 7],
        [7, 7, 7]])


random 한 텐서 생성

In [66]:
# pytorch 사용 (표준)정규분포 따르는 random tensor 생성

import torch

random_tensor = torch.randn(2,3)
print(random_tensor)
# torch.randn() 함수 사용, 2x3 행렬 생성
# 평균 0, 표준편차 1인 무작위 숫자 추출
# 각 원소는 [-1,1] 사이 random한 값 가짐

tensor([[-0.0994, -0.7822,  0.2217],
        [ 0.2520,  1.0464,  0.0057]])


In [68]:
import torch

# randn_like()
# 위에서 생성된 random_tensor 같은 크기인 2행 3열 랜덤 텐서 생성

torch.randn_like(random_tensor)

tensor([[ 0.1566, -0.4140,  0.7502],
        [ 0.7817, -1.0398, -0.3238]])

### `Tip!`


주요 특징
- 크기 유지: tensor_like는 random_tensor와 정확히 같은 크기(2x3)를 가집니다.
- 독립적인 랜덤 값: 생성된 값들은 random_tensor의 값들과 완전히 독립적입니다.
- 데이터 타입 일치: tensor_like는 random_tensor와 동일한 데이터 타입을 가집니다.
- GPU 호환성: 만약 random_tensor가 GPU에 있다면, tensor_like도 자동으로 GPU에 생성됩니다.


※ 이러한 기능은 딥러닝 모델에서 가중치 초기화나 노이즈 생성 등 다양한 상황에서 유용하게 사용될 수 있습니다.


In [73]:
import torch

# rand(행,열) [0,1]사이 실수값으로 채워진 텐서
tensor_rand = torch.rand(2,3)
print(tensor_rand)
print()

tensor_arange = torch.arange(1,7).reshape(2,3)
print(tensor_arange)

tensor([[0.3487, 0.7472, 0.9977],
        [0.9499, 0.4656, 0.4905]])

tensor([[1, 2, 3],
        [4, 5, 6]])


텐서 속성

- 텐서의 차원을 확인하는 dim() 메서드가 있습니다. 이는 텐서의 rank라고도 불립니다.
- 텐서의 형상(shape)을 확인하는 shape 속성이 있습니다. 이는 각 차원의 크기를 튜플 형태로 반환합니다.
- 텐서의 크기를 확인하는 size() 메서드도 있습니다. 이는 shape와 동일한 정보를 반환합니다.
- 데이터타입 자료형을 확인하는 dtype 속성은 datatype() 속성이며, 이를 통해 텐서의 데이터 타입(예: 정수, 실수, 불리언 등)을 알 수 있습니다.
- 텐서가 저장된 장치(CPU 또는 GPU)를 확인하는 device 속성이 있습니다.
- 텐서의 총 원소 개수를 반환하는 numel() 메서드도 유용합니다.



In [76]:
import torch

x = torch.randn(3,4,5)
print(x)
print()

tensor([[[ 0.2441,  0.5469, -0.6104,  0.8866, -0.1046],
         [-1.3654,  0.4084, -0.7749, -0.0150,  0.4486],
         [ 1.5015, -0.0578,  1.5913,  0.2432,  0.0785],
         [-0.7105,  0.5821,  0.6361, -0.5646,  0.8442]],

        [[-1.9472,  0.3906, -0.0061,  0.1011,  1.3897],
         [ 0.0116,  2.2066,  0.5024,  0.5005,  0.9226],
         [ 0.2844, -0.2382,  0.4580, -1.0130, -0.0528],
         [ 0.8406,  0.2552, -1.4732, -1.4044, -0.7633]],

        [[ 0.5852, -0.6829,  0.3760, -1.1565,  1.1612],
         [-0.1944,  0.0049, -0.1682,  1.1582, -1.5512],
         [-1.6818,  1.2012,  0.4599,  0.4898, -0.4916],
         [ 0.3682,  1.3297, -2.2880, -0.6754,  0.4935]]])



In [84]:
print(x.dim())  # 텐서의 차원 수
print(x.shape)  # 각 차원의 크기 (튜플 형태로 반환)
print(x.size()) # 각 차원의 크기 (튜플 형태로 반환)
print(x.dtype)  # data type
print(x.device) # 텐서가 저장된 장치 (cpu/gpu)
print(x.numel())# (3,4,5) >> 원소의 개수 number of elements

3
torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.float32
cpu
60


In [90]:
import torch

a = torch.tensor([1,2,3,4,5])   # 1차원 텐서
print(a.size()) # torch.Size([5]) : 5개의 정수 원소
print(a.shape)
print(a.dim())  # 차원
print(a.ndimension()) # 차원
print(a.dtype)

torch.Size([5])
torch.Size([5])
1
1
torch.int64


In [94]:
import torch

x4 = torch.FloatTensor([[1,2],[3,4]])

print(x4.size())
print(x4.shape)
print(x4.dim())
print(x4.ndimension())
print(x4.dtype)

torch.Size([2, 2])
torch.Size([2, 2])
2
2
torch.float32


In [97]:
import torch

x5 = torch.FloatTensor([[[1,2,3],[4,5,6],[7,8,9]]])

print(x5)
print()
print(x5.size())
print(x5.shape)
print(x5.dim())
print(x5.ndimension())
print(x5.dtype)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
3
3
torch.float32


In [102]:
# 행렬 곱셈 (dot product)

import torch

a = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
b = torch.tensor([[[7,8],[9,10],[11,12]]])

print(a)
print()
print(b)
print()

# matmul : matrix multiplcation 행렬 곱
c = torch.matmul(a,b)
print(c)
print(c.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([[[ 7,  8],
         [ 9, 10],
         [11, 12]]])

tensor([[[ 58,  64],
         [139, 154],
         [220, 244]]])
torch.Size([1, 3, 2])


In [109]:
import torch

tensor1 = torch.tensor([1,2,3])
print(tensor1)
print()

tensor2 = torch.zeros(3,3)
print(tensor2)
print()

tensor3 = torch.ones(2,2)
print(tensor3)
print()

tensor4 = torch.rand(3,3)
print(tensor4)

tensor([1, 2, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[0.2795, 0.7664, 0.7381],
        [0.5011, 0.8342, 0.0501],
        [0.7440, 0.5886, 0.0412]])


In [118]:
print(tensor4)
print()
tensor5 = tensor4.reshape(1,9)  # 2차원
print(tensor5)
print()
tensor6 = tensor4.view(-1)  # 1차원
print(tensor6)
print()
tensor7 = tensor4.t()
print(tensor7)

tensor([[0.2795, 0.7664, 0.7381],
        [0.5011, 0.8342, 0.0501],
        [0.7440, 0.5886, 0.0412]])

tensor([[0.2795, 0.7664, 0.7381, 0.5011, 0.8342, 0.0501, 0.7440, 0.5886, 0.0412]])

tensor([0.2795, 0.7664, 0.7381, 0.5011, 0.8342, 0.0501, 0.7440, 0.5886, 0.0412])

tensor([[0.2795, 0.5011, 0.7440],
        [0.7664, 0.8342, 0.5886],
        [0.7381, 0.0501, 0.0412]])


데이터 타입 지정 텐서 생성
- 정수형, 실수형

In [124]:
import torch

float_tensor = torch.tensor([1.5,2.5,3.5], dtype=torch.float32)
print(float_tensor)
print()
int_tensor = torch.tensor([1,2,3], dtype=torch.int64)
print(int_tensor)

tensor([1.5000, 2.5000, 3.5000])

tensor([1, 2, 3])


텐서 연산

#### 기본 연산


-   **덧셈과 뺄셈**: 같은 크기의 텐서 간에 요소별로 수행됩니다.
-   **요소별 곱셈**: 두 텐서의 대응하는 요소끼리 곱합니다.
-   **스칼라 곱**: 텐서의 모든 요소에 스칼라 값을 곱합니다.


#### 행렬 곱셈


-   행렬 곱셈은 `torch.matmul()` 또는 `@` 연산자를 사용합니다.
-   왼쪽 행렬의 열 수와 오른쪽 행렬의 행 수가 일치해야 합니다.
-   결과 행렬의 크기는 (왼쪽 행렬의 행 수) x (오른쪽 행렬의 열 수)가 됩니다.


#### 고급 연산


-   **전치(Transpose)**: 행과 열을 바꾸는 연산으로, `t()` 메서드를 사용합니다.
-   **차원 축소**: `sum()`, `mean()` 등의 함수로 특정 차원을 따라 값을 집계합니다.
-   **브로드캐스팅**: 크기가 다른 텐서 간의 연산을 자동으로 조정합니다.


#### 비선형 활성화 함수


-   ReLU, Sigmoid, Tanh 등의 함수를 텐서에 적용하여 비선형성을 도입합니다.


이러한 연산들은 신경망의 순전파와 역전파 과정에서 핵심적인 역할을 합니다.


효율적인 텐서 연산은 딥러닝 모델의 성능과 학습 속도에 직접적인 영향을 미칩니다.

