<a href="https://colab.research.google.com/github/kny1209/test2/blob/main/%EA%B0%95%EC%9D%98_8%EA%B8%B0_AI%EA%B0%9C%EB%A1%A0_1%EC%B0%A8%EC%8B%9C_02_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!sudo apt-get install -y fonts-nanum* | tail -n 1
!sudo fc-cache -fv
!rm -rf ~/.cache/matplotlib

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 4.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 39 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no suc

In [2]:
# 라이브러리 임포트


%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display


# 폰트 관련 용도
import matplotlib.font_manager as fm


# 나눔 고딕 폰트의 경로 명시
path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
font_name = fm.FontProperties(fname=path, size=10).get_name()

In [4]:
# 파이토치 관련 라이브러리
import torch

In [5]:
# 기본 폰트 설정
plt.rcParams['font.family'] = font_name


# 기본 폰트 사이즈 변경
plt.rcParams['font.size'] = 14


# 기본 그래프 사이즈 변경
plt.rcParams['figure.figsize'] = (6,6)


# 기본 그리드 표시
# 필요에 따라 설정할 때는, plt.grid()
plt.rcParams['axes.grid'] = True


# 마이너스 기호 정상 출력
plt.rcParams['axes.unicode_minus'] = False


# 넘파이 부동소수점 자릿수 표시
np.set_printoptions(suppress=True, precision=4)

리스트와 넘파이 차이

In [1]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np

np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

넘파이 변수 간

In [4]:
x = np.array([4,5,6])

y = x

print(x)
print(y)

[4 5 6]
[4 5 6]


In [5]:
x[1]

np.int64(5)

In [6]:
# x의 특정 요소 변경
x[1] = -1

print(x)
print(y)

[ 4 -1  6]
[ 4 -1  6]


In [7]:
x = np.array([4,5,6])

y = x.copy()

x[1] = -1

print(x)
print(y)

[ 4 -1  6]
[4 5 6]


텐서와 넘파이 변수 간

In [8]:
import torch

torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [9]:
import torch

torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [10]:
torch.ones(5).data.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [16]:
import torch

x1 = torch.ones(5)
print(x1.shape)
# x1 : shape = [5]가 되는 모든 값이 1인 텐서

print(x1)

x2 = x1.data.numpy()
print(x2)

torch.Size([5])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
# x1 값 변경
x1[1] = -1

print(x1)
print(x2)   # x2의 값도 같이 변함

tensor([ 1., -1.,  1.,  1.,  1.])
[ 1. -1.  1.  1.  1.]


In [20]:
# x1 : tensor : 3차원 이상(GPU용)

x1 = torch.ones(5)

# x2 : x1을 copy >> numpy(CPU용)
x2 = x1.data.numpy().copy()

x1[1] = -1

print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]
