<a href="https://colab.research.google.com/github/kny1209/test2/blob/main/%EA%B0%95%EC%9D%98_8%EA%B8%B0_AI%EA%B0%9C%EB%A1%A0_2%EC%B0%A8%EC%8B%9C_01_numpy_%5BLiveCoding%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# numpy 부동소수점 자리 표시
np.set_printoptions(precision = 3, suppress=True)

In [6]:
n1 = np.array([1,2,3,4,5,6])
print(n1)

[1 2 3 4 5 6]


In [7]:
# 요소수 확인
print(n1.shape)
# (6,) 1차원

(6,)


In [8]:
len(n1)

6

In [10]:
n2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(n2.shape)
# 2차원 (4,3)
# (수학) 4행 3열 (행렬) 4개의 배열, 각 배열 3개의 원소가 있음 -> 원소 개수 12개

(4, 3)


In [11]:
len(n2)

4

##zeors, ones 함수 이용

In [13]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
n3 = np.zeros([5])
print(n3.shape) # 1차원

(5,)


In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((2,3))  # 2차원

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
n4 = np.ones((2,3))
print(n4)
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [21]:
# 모든 요소 정규분포 따르는 변수와 3개 행렬
np.random.rand(2,3,4)
# random : 무작위, 임의적 >> 일반화
# rand(normalize) >> 정규분포 평균 : 0 , 표준편차 : 1
# 표준화 (x-x_bar) / sigma  : 평균 : 0 , 표준편차 : 1로 만듬
# >> x : 원래값, x_bar : 평균, sigma : 편차
# 정규화 (x-x_min) / (x_max - x_min) : 데이터 범위 [0,1]로 만듬
# >> x : 원래값, x_min : 해당 속성(열) 최소값, x_max : 해당 속성(열) 최대값
# n으로 나눈다 n = len(x)
# (2,3,4) : 3개의 배열, 각 배열마다 4개의 원소 가지는 행렬이 2개

array([[[0.591, 0.682, 0.863, 0.112],
        [0.305, 0.548, 0.45 , 0.456],
        [0.56 , 0.958, 0.099, 0.638]],

       [[0.241, 0.143, 0.513, 0.926],
        [0.469, 0.872, 0.169, 0.779],
        [0.98 , 0.816, 0.131, 0.627]]])

In [22]:
n5 = np.random.rand(2,3,4)
print(n5.shape)

(2, 3, 4)


###그래프 출력용 수치 배열 생성

In [23]:
np.linspace(-1,1,11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [24]:
n6 = np.linspace(-1,1,11)
print(n6.shape)
# 1 차원

(11,)


In [25]:
n6.ndim # ndim : number of dimension 차원 수

1

In [31]:
np.arange(-1, 1.2, 0.2)

array([-1. , -0.8, -0.6, -0.4, -0.2, -0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

##조작 (manupulation)

In [32]:
# 특정 행,열 추출
print(n2)
print(n2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [37]:
n2[:, 0]

array([ 1,  4,  7, 10])

In [39]:
n2[:, 0].shape

(4,)

In [42]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
len(n2)

4

In [40]:
np.array([False,True, False, True])

array([False,  True, False,  True])

In [41]:
n7 = np.array([False,True, False, True])
n2[n7]  # mask추출

array([[ 4,  5,  6],
       [10, 11, 12]])

In [43]:
n8 = n2[n7]
n8.shape

(2, 3)

#reshape(**)

In [45]:
# 초기 변수 1개 배열
np.array(range(24))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
n9 = np.array(range(24))
n9.shape
# 1차원 벡터 **(요소 24개)

(24,)

In [49]:
n9.reshape(3,-1)    # -1 : 전체 원소 개수 맞춰서 알아서 채워라
# 2차원 (3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [56]:
# n9.reshape(5,-1)
# ValueError: cannot reshape array of size 24 into shape (5,newaxis)


In [50]:
n9.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [53]:
# n9.reshape(3,7)
# ValueError: cannot reshape array of size 24 into shape (3,7)

In [57]:
n9.reshape(2,2,-1)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [60]:
n9.reshape(2,2,6).shape
# 3차원 축 3개
# >> 배열 2개, 각 배열이 6개 원소를 가지 행렬이 2개

(2, 2, 6)

In [61]:
n9.reshape(2,2,2,-1)    # 4차원

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [64]:
n9.reshape(2,2,2,-1)[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
# -1을 지정해서 자동으로 계산
n9.reshape(2,-1,3) # (2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

##축 교체하기

In [67]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
n2.shape

(4, 3)

In [66]:
# 전치행렬(행과 열을 바꾸어 줌, 위치를 바꾸다)
# T : transpose
n2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [69]:
n2.T.shape

(3, 4)

In [72]:
n9.reshape(2,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [74]:
n10 = n9.reshape(2,-1,4)
n10.shape

(2, 3, 4)

In [77]:
np.transpose(n10)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [78]:
np.transpose(n10).shape

(4, 3, 2)

In [79]:
np.transpose(n10,(1,2,0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [80]:
# (2, 3, 4)
np.transpose(n10,(1,2,0)).shape

(3, 4, 2)

In [82]:
# (2, 3, 4)
np.transpose(n10,(2,1,0)).shape

(4, 3, 2)

In [99]:
one_d = np.array([1,2,3,4,5])
one_d

array([1, 2, 3, 4, 5])

In [100]:
one_d.shape

(5,)

In [101]:
one_d.T

array([1, 2, 3, 4, 5])

In [102]:
np.reshape(one_d, (5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
two_d = np.reshape(one_d, (5,1))
two_d.shape

(5, 1)

In [105]:
two_d.T # 조

array([[1, 2, 3, 4, 5]])

In [106]:
two_d.T.shape

(1, 5)

##행렬 연결하기

In [107]:
np.array(range(1,7))

array([1, 2, 3, 4, 5, 6])

In [108]:
np.array(range(1,7)).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.array(range(1,7)).reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.array(range(1,7)).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
n13 = np.array(range(1,7)).reshape(2,-1)
n14 = np.array(range(7,13)).reshape(2,-1)

print(n13)
print()
print(n14)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [114]:
# 3요소 벡터
np.array(range(14,17))
n15 = np.array(range(14,17))
n15

array([14, 15, 16])

In [115]:
# 행렬과 행렬 연결 (n13, n14)
# vstack : vertically stack 수직으로 쌓음
np.vstack([n13,n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [116]:
# hstack : horizontally stack 수평으로 쌓음
np.hstack([n13,n14])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [117]:
# concatenate 합치다
# (default) axis=0 서로 다른 행끼리, 행세열가 (행 세로방향)
np.concatenate([n13,n14])
# vstack 동일

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [119]:
np.concatenate([n13,n14],axis=1)    # 행세 부~ 열가 에이취~
# hstack 동일

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [120]:
np.concat([n13,n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [121]:
np.concat([n13,n14],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 연산

In [123]:
print(n13)
print()
print(n14)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [124]:
n13 + n14

array([[ 8, 10, 12],
       [14, 16, 18]])

In [125]:
n15 = n13 + n14
n15

array([[ 8, 10, 12],
       [14, 16, 18]])

##브로드캐스팅

In [126]:
n1  # 1차원

array([1, 2, 3, 4, 5, 6])

In [127]:
# 모든 요소에 같은 값을 빼고 싶음
n1-3

array([-2, -1,  0,  1,  2,  3])

##유니버셜 함수

In [128]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [129]:
np.linspace(0,2*np.pi,5)

array([0.   , 1.571, 3.142, 4.712, 6.283])

In [131]:
x = np.linspace(0,2*np.pi,5)
y = np.sin(x)
print(y)

[ 0.  1.  0. -1. -0.]


#집계함수(**)

In [132]:
n1

array([1, 2, 3, 4, 5, 6])

In [133]:
np.sum(n1)

np.int64(21)

In [134]:
np.mean(n1)

np.float64(3.5)

In [135]:
np.max(n1)  # 함수형

np.int64(6)

In [140]:
max(n1) # 파이썬 제공 기본 함수

np.int64(6)

In [139]:
# np.min(n1)
n1.min()    # 메소드형
n1.min().round(2) #method chaning

np.int64(1)

##응용 예시

In [144]:
# 두 변수를 비교해서 일치하는 개수로 정확도 계산


# 2개의 넘파이 배열 준비


# 정답
yt = np.array([1,1,0,1,0,1,1,0,1,0])


# 예측
yp = np.array([1,1,0,1,0,1,0,1,1,1])

In [145]:
# 정답과 예측 잘 맞나 비교
(yt == yp)

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False])

In [146]:
matched = (yt == yp)
matched.sum()

np.int64(7)

In [147]:
# 맞은 갯수 (정답 수)
correct = matched.sum()

# 전체 수
total = len(matched)

# 정확도
accuracy = correct / total
print(accuracy)

0.7


In [148]:
print(f'정답수:{correct}, 전체개수:{total}, 정확도:{accuracy*100}%')

정답수:7, 전체개수:10, 정확도:70.0%


##벡터 값을 1차 함수로 변환 [0,1] 범위 제한

In [149]:
n1

array([1, 2, 3, 4, 5, 6])

In [151]:
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

6 1


In [153]:
# 변환 >> 정규화
(n1 - n1_min) / (n1_max - n1_min)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])